language: node_js

env:
  - REACT_VERSION=15.6.1
  - REACT_VERSION=15.4.0

node_js:
  - "4"
  - "6"
  - "8"

before_install:
  - npm install react@$REACT_VERSION react-dom@$REACT_VERSION

script:
  - npm run lint
  - npm run test:cov

after_success:
  - npm install codecov
  - $(npm bin)/codecov
