language: node_js

node_js:
  - "5"

before_install:
  - npm install react react-dom

script:
  - npm run lint
  - npm run test:cov

after_success:
  - npm install coveralls
  - cat ./coverage/lcov.info | $(npm bin)/coveralls
