language: node_js

env:
  - REACT_VERSION=15
  - REACT_VERSION=0.14

node_js:
  - "5"

before_install:
  - npm install react@$REACT_VERSION react-dom@$REACT_VERSION

script:
  - npm run lint
  - npm run test:cov

after_success:
  - npm install coveralls
  - cat ./coverage/lcov.info | $(npm bin)/coveralls
